### ISSUE TITLE
Improve lighthouse score 

### ISSUE THREAD

**Issue by cesarsiguencia** [cesarsiguencia/10000-days#13]
- Some images missing alt descriptions / incorrect aspect ratio
- Need a meta description
- Need unique ids

**Comment by sol-jr** [comment]
Hello if this issue is still open I would like to work on this.

**Comment by cesarsiguencia** [comment]
> Hello if this issue is still open I would like to work on this.

Thanks Dwayne! I complete this about two days ago and happy with the result, but appreciate you reaching out regardless.
